### ISSUE TITLE
Ruby < 2.5 incompatibilities

### ISSUE THREAD

**Issue by mikecmpbll** [chaadow/activestorage-openstack#16]
Since this change https://github.com/chaadow/activestorage-openstack/commit/5f9ddc1736d0f879fc04b70949d630e3967840f7#diff-c18a1a9ef90f1c7dd12be30eab496f09L49 the gem is no longer compatible with rubies less than 2.5, since ruby 2.5 added the block rescue syntax which you're using since gem version 0.2.0.

solution would be to use ruby version dependency on rubygems i guess? :/

**Comment by chaadow** [comment]
Yes i'm even using safe navigation, which is introduced in ruby 2.3.0 
Knowing that rails 5.2 requires ruby 2.2.2 at least, I guess I should make this gem compatible with that specific ruby version.

Ruby version dependency should also be enforced. I'll fix that ASAP

**Comment by chaadow** [comment]
@mikecmpbll fixed in `v0.5.0`
