### ISSUE TITLE
Choice to delete variants

### ISSUE THREAD

**Issue by vadimstroganov** [chaadow/activestorage-openstack#26]
I chose an OpenStack provider that does not give the user permission to bulk-delete files.

How do you look at adding an option to choose how to delete files? Delete one by one, or bulk-delete.

I am talking about this method: https://github.com/chaadow/activestorage-openstack/blob/master/lib/active_storage/service/open_stack_service.rb#L67

**Comment by chaadow** [comment]
Yes, you can actually achieve that, either deleting manually using the my service class, or bulk deleting, by providing a prefix. You can have a look at the tests to see an implementation [here](https://github.com/chaadow/activestorage-openstack/blob/91f002351b35d19e1ce3a372221b6da324390a35/test/active_storage/service/open_stack_service_test.rb#L149)

**Comment by vadimstroganov** [comment]
I want to do something like this:

if option bulk-delete = false, then
```
filtered_files.each do |file_key|
   delete(file_key)
end
```

else

```
client.delete_multiple_objects(container, filtered_files)
```

**Comment by vadimstroganov** [comment]
I can do it and create PR

**Comment by chaadow** [comment]
@vadimstroganov   Sorry you can implement this logic in your application by accessing the service instance like this : `blob.service`. and from there you can access the method like so :
 - `blob.service.delete` to individually delete a blob
- `blob.service.client.delete_multiple_objects` to bulk delete.

If you need more control you will have to do this.

Also you can reopen the class and override any method you want like so : 
```ruby
class ActiveStorage::Service::OpenStack
def delete_prefixed(...)
  # my logic
end
```
